/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

// 1. Changed "export function" to "const Computer =" so we can default export it at the bottom
const Computer = (props) => {
  const { nodes, materials } = useGLTF('/models/computer-optimized-transformed.glb')
  
  return (
    <group {...props} dispose={null}>
      {/* 2. Fixed Typos: "castshadows" -> "castShadow", "receiveShadows" -> "receiveShadow" */}
      <group position={[-4.005, 67.549, 58.539]}>
        <mesh 
          castShadow 
          receiveShadow 
          geometry={nodes.Cube000_ComputerDesk_0001_1.geometry} 
          material={materials['ComputerDesk.001']} 
        />
        <mesh 
          castShadow 
          receiveShadow 
          geometry={nodes.Cube000_ComputerDesk_0001_2.geometry} 
          material={materials['FloppyDisk.001']} 
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/computer-optimized-transformed.glb')

// 3. ADD THIS: This makes "import Computer from './Computer'" work!
export default Computer;